/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShowsRouteImport } from './routes/shows'
import { Route as PodcastsRouteImport } from './routes/podcasts'
import { Route as ListenRouteImport } from './routes/listen'
import { Route as GetFeaturedRouteImport } from './routes/get-featured'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as BooksRouteImport } from './routes/books'
import { Route as AuthorsRouteImport } from './routes/authors'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsRoute = ShowsRouteImport.update({
  id: '/shows',
  path: '/shows',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastsRoute = PodcastsRouteImport.update({
  id: '/podcasts',
  path: '/podcasts',
  getParentRoute: () => rootRouteImport,
} as any)
const ListenRoute = ListenRouteImport.update({
  id: '/listen',
  path: '/listen',
  getParentRoute: () => rootRouteImport,
} as any)
const GetFeaturedRoute = GetFeaturedRouteImport.update({
  id: '/get-featured',
  path: '/get-featured',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsRoute = AuthorsRouteImport.update({
  id: '/authors',
  path: '/authors',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/authors': typeof AuthorsRoute
  '/books': typeof BooksRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/get-featured': typeof GetFeaturedRoute
  '/listen': typeof ListenRoute
  '/podcasts': typeof PodcastsRoute
  '/shows': typeof ShowsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/authors': typeof AuthorsRoute
  '/books': typeof BooksRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/get-featured': typeof GetFeaturedRoute
  '/listen': typeof ListenRoute
  '/podcasts': typeof PodcastsRoute
  '/shows': typeof ShowsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/authors': typeof AuthorsRoute
  '/books': typeof BooksRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/get-featured': typeof GetFeaturedRoute
  '/listen': typeof ListenRoute
  '/podcasts': typeof PodcastsRoute
  '/shows': typeof ShowsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/authors'
    | '/books'
    | '/community'
    | '/contact'
    | '/get-featured'
    | '/listen'
    | '/podcasts'
    | '/shows'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/authors'
    | '/books'
    | '/community'
    | '/contact'
    | '/get-featured'
    | '/listen'
    | '/podcasts'
    | '/shows'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/authors'
    | '/books'
    | '/community'
    | '/contact'
    | '/get-featured'
    | '/listen'
    | '/podcasts'
    | '/shows'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthorsRoute: typeof AuthorsRoute
  BooksRoute: typeof BooksRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  GetFeaturedRoute: typeof GetFeaturedRoute
  ListenRoute: typeof ListenRoute
  PodcastsRoute: typeof PodcastsRoute
  ShowsRoute: typeof ShowsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows': {
      id: '/shows'
      path: '/shows'
      fullPath: '/shows'
      preLoaderRoute: typeof ShowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcasts': {
      id: '/podcasts'
      path: '/podcasts'
      fullPath: '/podcasts'
      preLoaderRoute: typeof PodcastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listen': {
      id: '/listen'
      path: '/listen'
      fullPath: '/listen'
      preLoaderRoute: typeof ListenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-featured': {
      id: '/get-featured'
      path: '/get-featured'
      fullPath: '/get-featured'
      preLoaderRoute: typeof GetFeaturedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors': {
      id: '/authors'
      path: '/authors'
      fullPath: '/authors'
      preLoaderRoute: typeof AuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthorsRoute: AuthorsRoute,
  BooksRoute: BooksRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  GetFeaturedRoute: GetFeaturedRoute,
  ListenRoute: ListenRoute,
  PodcastsRoute: PodcastsRoute,
  ShowsRoute: ShowsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
